modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="onc"
version="1.0.0"
displayName="Oxygen Not Crafted"
displayURL="https://mcreator.net"
credits="MCreator, Elliot, Cubic"
authors="Cubic, Elliot"
description="No more breathing in the void!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.onc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.onc]]
    modId="ldlib_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.onc]]
    modId="photon_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

